### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by Nosnahc** [birdybirdonline/Linux-Arctis-7-Plus-ChatMix#1]
Hi,
first of all, thank you for your work!!

This soft doesn't look to work well for me. 
I got only Digital/Analog Output in pavucontrol and can't separate Discord to one and my game to another.
Maybe the problem is between the seat and the keyboard but I don't think so.

**Comment by birdybirdonline** [comment]
Hey,

Did you follow the readme exactly?

Hhave you tried manually running `Arctis_7_Plus_ChatMix.py`?

Do you have any info from `sysctl` or `journalctl` that might help?

**Comment by Nosnahc** [comment]
The systemctl command give :
`arctis7pcm.service - Arctis 7+ ChatMix
     Loaded: loaded (/home/nosnahc/.config/systemd/user/arctis7pcm.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2023-03-19 17:03:13 CET; 14s ago
   Main PID: 2630 (python3)
      Tasks: 3 (limit: 18759)
     Memory: 6.5M
        CPU: 72ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/arctis7pcm.service
             └─2630 /usr/bin/python3 /home/nosnahc/.local/bin/Arctis_7_Plus_ChatMix.py

mars 19 17:03:13 nosnahc-Legion-5-Mint python3[2630]:     INFO | ---------------------------------------------
mars 19 17:03:13 nosnahc-Legion-5-Mint python3[2630]:     INFO | Arctis 7+ ChatMix Enabled!
mars 19 17:03:13 nosnahc-Legion-5-Mint python3[2630]:     INFO | ---------------------------------------------
mars 19 17:03:16 nosnahc-Legion-5-Mint python3[2666]: Échec lors de l’obtention des informations sur la destination : Aucune entité de ce type`


When I run manually the .py I get :

`    INFO | Initializing ac7pcm...
    INFO | default sink identified as alsa_output.usb-SteelSeries_Arctis_7_-00.iec958-stereo
    INFO | Arctis sink identified as alsa_output.usb-SteelSeries_Arctis_7_-00.iec958-stereo
    INFO | Attempted to destroy old VAC sinks at init but none existed
    INFO | Creating VACS...
    INFO | Assigning VAC sink monitors output to default device...
failed to link ports: Aucun fichier ou dossier de ce type
failed to link ports: Aucun fichier ou dossier de ce type
failed to link ports: Aucun fichier ou dossier de ce type
failed to link ports: Aucun fichier ou dossier de ce type
Échec : Aucune entité de ce type
    INFO | Reading modulator USB input started
    INFO | ---------------------------------------------
    INFO | Arctis 7+ ChatMix Enabled!
    INFO | ---------------------------------------------
CRITICAL | USB input/output error - likely disconnect
`

**Comment by birdybirdonline** [comment]
I've just pushed a small hotfix on the way the device detection exception is handled. Please can you follow the [readme](https://github.com/birdybirdonline/Linux-Arctis-7-Plus-ChatMix#readme) instructions to uninstall and reinstall.

Also, after reinstalling try the following steps:

1. Reboot your machine
2. switch the headset on (and wear it)
3. disconnect the usb dongle from its cable (the headset should beep once)
4. wait a moment, then reconnect the dongle (the headset should beep a second time)
5. check `systemctl` again to see if the unhandled errors are still appearing.

**Comment by Nosnahc** [comment]
Thank you very much for your kick hotfix!! but I have the same error after following all the steps.

    mars 19 19:48:06 nosnahc-Legion-5-Mint python3[2694]: Échec lors de l’obtention des informations sur la destination : Aucune entité de ce type
    mars 19 19:48:06 nosnahc-Legion-5-Mint python3[2696]: Échec lors de l’obtention des informations sur la destination : Aucune entité de ce type
    mars 19 19:48:06 nosnahc-Legion-5-Mint python3[2698]: Échec lors de l’obtention des informations sur la destination : Aucune entité de ce type
    mars 19 19:48:06 nosnahc-Legion-5-Mint python3[2700]: Échec lors de l’obtention des informations sur la destination : Aucune entité de ce type
    mars 19 19:48:06 nosnahc-Legion-5-Mint python3[2702]: Échec lors de l’obtention des informations sur la destination : Aucune entité de ce type
    mars 19 19:48:06 nosnahc-Legion-5-Mint python3[2704]: Échec lors de l’obtention des informations sur la destination : Aucune entité de ce type
    mars 19 19:48:06 nosnahc-Legion-5-Mint python3[2706]: Échec lors de l’obtention des informations sur la destination : Aucune entité de ce type
    mars 19 19:48:06 nosnahc-Legion-5-Mint python3[2708]: Échec lors de l’obtention des informations sur la destination : Aucune entité de ce type
    mars 19 19:48:07 nosnahc-Legion-5-Mint python3[2710]: Échec lors de l’obtention des informations sur la destination : Aucune entité de ce type
    mars 19 19:48:07 nosnahc-Legion-5-Mint python3[2712]: Échec lors de l’obtention des informations sur la destination : Aucune entité de ce type

**Comment by birdybirdonline** [comment]
Can you please tell me what distro you are running? And is your headset definitely the 7+ version?

**Comment by Nosnahc** [comment]
Yes, my headset is a 7+!
I'm on linux Mint 21.1

**Comment by birdybirdonline** [comment]
I believe your distro may be the issue, please see [this reddit post](https://www.reddit.com/r/linuxmint/comments/yj9h4n/comment/iuob8j9/?utm_source=share&utm_medium=web2x&context=3).

Our chatmix scripts depend on Pipewire; this will be why it is failing for you, as the virutal devices it creates won't exist without pipewire.

Suggested fixes might be to see if you can install pipewire first on your system and then reinstall chatmix. We don't have any plans to create a non-pipewire version at the present time. Sorry I can't be more help right now!

**Comment by Nosnahc** [comment]
Thann you very much.
I'll look with pipewire.
Have a nice day
